/**
 * src/components/EventPage.jsx
 *
 * Purpose: Dynamic SEO-optimized event detail page for economic events.
 * Provides individual indexable pages for each event in the economicEventDescriptions collection.
 * Supports EN/ES/FR translations with proper hreflang tags and structured data.
 *
 * Route: /events/:eventId (EN), /events/:eventId?lang=es (ES), /events/:eventId?lang=fr (FR)
 * SEO: 159 static pages (53 events × 3 languages) generated by prerender.mjs
 *
 * Changelog:
 * v1.0.0 - 2026-02-02 - Initial implementation with SEO metadata, JSON-LD structured data, 
 *                       multi-language support, and mobile-first responsive design.
 */

import { useState, useCallback, useMemo, Suspense, lazy } from 'react';
import { useParams, useNavigate, Link as RouterLink } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
    Box,
    Typography,
    Paper,
    Chip,
    Button,
    Alert,
    Grid,
    Card,
    CardContent,
    Breadcrumbs,
    Link,
} from '@mui/material';
import PropTypes from 'prop-types';
import {
    TrendingUp as TrendingUpIcon,
    Schedule as ScheduleIcon,
    Category as CategoryIcon,
    Source as SourceIcon,
    ArrowBack as ArrowBackIcon,
    CalendarMonth as CalendarIcon,
    ShowChart as ShowChartIcon,
} from '@mui/icons-material';
import SEO from './SEO';
import PublicLayout from './PublicLayout';
import { useAuth } from '../contexts/AuthContext';
import useAppBarNavItems from '../hooks/useAppBarNavItems.jsx';
import { SITE_URL, DEFAULT_OG_IMAGE, buildWebPageBreadcrumbs } from '../utils/seoMeta';

// Event descriptions data (loaded from local JSON at build time for SSR, fetched at runtime for SPA)
import eventDescriptionsData from '../../data/economicEventDescriptions.json';

const SettingsSidebar2 = lazy(() => import('./SettingsSidebar2'));
const AuthModal2 = lazy(() => import('./AuthModal2'));

/**
 * Impact color mapping
 */
const impactColors = {
    high: { bg: 'error.light', text: 'error.contrastText', border: 'error.main' },
    medium: { bg: 'warning.light', text: 'warning.contrastText', border: 'warning.main' },
    low: { bg: 'success.light', text: 'success.contrastText', border: 'success.main' },
};

/**
 * Get localized content for an event
 */
const getLocalizedContent = (event, lang = 'en') => {
    const i18n = event?.i18n || {};
    const langContent = i18n[lang] || i18n.en || {};

    return {
        description: langContent.description || event?.description || '',
        tradingImplication: langContent.tradingImplication || event?.tradingImplication || '',
        releaseTime: langContent.releaseTime || event?.releaseTime || '',
        keyThresholds: langContent.keyThresholds || event?.keyThresholds || {},
    };
};

/**
 * Build event page structured data (JSON-LD)
 */
const buildEventStructuredData = (event, localizedContent, lang) => {
    const eventUrl = `${SITE_URL}/events/${event.id}${lang !== 'en' ? `?lang=${lang}` : ''}`;

    return [
        // Article schema for event explanation
        {
            '@context': 'https://schema.org',
            '@type': 'Article',
            headline: `${event.name} - Economic Event Guide`,
            description: localizedContent.description,
            url: eventUrl,
            inLanguage: lang,
            publisher: {
                '@type': 'Organization',
                name: 'Time 2 Trade',
                url: SITE_URL,
            },
            author: {
                '@type': 'Organization',
                name: 'Time 2 Trade',
            },
            datePublished: '2026-01-01',
            dateModified: new Date().toISOString().split('T')[0],
            mainEntityOfPage: eventUrl,
            image: DEFAULT_OG_IMAGE,
        },
        // Breadcrumb schema
        buildWebPageBreadcrumbs([
            { name: 'Home', url: SITE_URL },
            { name: 'Economic Events', url: `${SITE_URL}/calendar` },
            { name: event.name, url: eventUrl },
        ]),
    ];
};

/**
 * Info card component for event details
 */
const InfoCard = ({ icon, title, children, sx = {} }) => (
    <Card
        elevation={0}
        sx={{
            border: '1px solid',
            borderColor: 'divider',
            borderRadius: 2,
            height: '100%',
            ...sx,
        }}
    >
        <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5 }}>
                {icon}
                <Typography variant="subtitle1" fontWeight={600} color="text.primary">
                    {title}
                </Typography>
            </Box>
            {children}
        </CardContent>
    </Card>
);

InfoCard.propTypes = {
    icon: PropTypes.node.isRequired,
    title: PropTypes.string.isRequired,
    children: PropTypes.node.isRequired,
    sx: PropTypes.object,
};

InfoCard.propTypes = {
    icon: PropTypes.node.isRequired,
    title: PropTypes.string.isRequired,
    children: PropTypes.node.isRequired,
    sx: PropTypes.object,
};

/**
 * Key thresholds display component
 */
const KeyThresholdsDisplay = ({ thresholds, t }) => {
    if (!thresholds || Object.keys(thresholds).length === 0) return null;

    const thresholdLabels = {
        strong: { label: t('eventPage.thresholds.strong', 'Strong'), color: 'success.main' },
        moderate: { label: t('eventPage.thresholds.moderate', 'Moderate'), color: 'warning.main' },
        weak: { label: t('eventPage.thresholds.weak', 'Weak'), color: 'error.main' },
    };

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            {Object.entries(thresholds).map(([key, value]) => {
                const config = thresholdLabels[key] || { label: key, color: 'text.secondary' };
                return (
                    <Box
                        key={key}
                        sx={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: 1,
                            p: 1,
                            borderRadius: 1,
                            bgcolor: 'action.hover',
                        }}
                    >
                        <Box
                            sx={{
                                width: 8,
                                height: 8,
                                borderRadius: '50%',
                                bgcolor: config.color,
                                flexShrink: 0,
                            }}
                        />
                        <Typography variant="body2" sx={{ fontWeight: 600, minWidth: 70 }}>
                            {config.label}:
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                            {value}
                        </Typography>
                    </Box>
                );
            })}
        </Box>
    );
};
KeyThresholdsDisplay.propTypes = {
    thresholds: PropTypes.object,
    t: PropTypes.func.isRequired,
};
/**
 * Event not found component
 */
const EventNotFound = ({ eventId, t, onBack }) => (
    <Box
        sx={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '60vh',
            p: 4,
            textAlign: 'center',
        }}
    >
        <Alert severity="warning" sx={{ mb: 3, maxWidth: 500 }}>
            <Typography variant="body1">
                {t('eventPage.notFound', 'Event not found: {{eventId}}', { eventId })}
            </Typography>
        </Alert>
        <Button
            variant="contained"
            startIcon={<ArrowBackIcon />}
            onClick={onBack}
            sx={{ textTransform: 'none' }}
        >
            {t('eventPage.backToCalendar', 'Back to Calendar')}
        </Button>
    </Box>
);

EventNotFound.propTypes = {
    eventId: PropTypes.string,
    t: PropTypes.func.isRequired,
    onBack: PropTypes.func.isRequired,
};

/**
 * EventPage Component
 *
 * Features:
 * - Dynamic SEO metadata per event
 * - Multi-language support (EN/ES/FR)
 * - JSON-LD structured data for search engines
 * - Mobile-first responsive design
 * - Proper hreflang tags for international SEO
 */
export default function EventPage() {
    const { eventId } = useParams();
    const navigate = useNavigate();
    const { t, i18n } = useTranslation('events');
    const currentLang = i18n.language || 'en';

    const { isAuthenticated } = useAuth();
    const [settingsOpen, setSettingsOpen] = useState(false);
    const [authModalOpen, setAuthModalOpen] = useState(false);

    const handleOpenSettings = useCallback(() => setSettingsOpen(true), []);
    const handleCloseSettings = useCallback(() => setSettingsOpen(false), []);
    const handleOpenAuth = useCallback(() => setAuthModalOpen(true), []);
    const handleCloseAuth = useCallback(() => setAuthModalOpen(false), []);
    const handleBackToCalendar = useCallback(() => navigate('/calendar'), [navigate]);

    // Find event from local data
    const event = useMemo(() => {
        if (!eventId) return null;
        return eventDescriptionsData.events.find(
            (e) => e.id === eventId || e.docId === eventId
        );
    }, [eventId]);

    // Get localized content
    const localizedContent = useMemo(
        () => (event ? getLocalizedContent(event, currentLang) : null),
        [event, currentLang]
    );

    // Build structured data
    const structuredData = useMemo(
        () => (event && localizedContent ? buildEventStructuredData(event, localizedContent, currentLang) : []),
        [event, localizedContent, currentLang]
    );

    // Navigation items
    const navItems = useAppBarNavItems({
        isAuthenticated,
        onOpenSettings: handleOpenSettings,
        onOpenAuth: handleOpenAuth,
    });

    // If no event found
    if (!event) {
        return (
            <PublicLayout
                navItems={navItems}
                onOpenAuth={handleOpenAuth}
                onOpenSettings={handleOpenSettings}
            >
                <EventNotFound eventId={eventId} t={t} onBack={handleBackToCalendar} />
            </PublicLayout>
        );
    }

    // SEO metadata
    const seoTitle = `${event.name} | ${t('eventPage.seoTitleSuffix', 'Economic Event Guide')} - Time 2 Trade`;
    const seoDescription = localizedContent.description.substring(0, 160);
    const seoPath = `/events/${eventId}`;

    // Impact styling
    const impactStyle = impactColors[event.impact] || impactColors.medium;

    return (
        <>
            <SEO
                title={seoTitle}
                description={seoDescription}
                path={seoPath}
                structuredData={structuredData}
                lang={currentLang}
                ogType="article"
            />

            <PublicLayout
                navItems={navItems}
                onOpenAuth={handleOpenAuth}
                onOpenSettings={handleOpenSettings}
            >
                <Box
                    sx={{
                        maxWidth: 1200,
                        mx: 'auto',
                        px: { xs: 2, sm: 3, md: 4 },
                        py: { xs: 2, md: 4 },
                        minHeight: 0,
                        overflowY: 'auto',
                        scrollbarWidth: 'thin',
                        scrollbarColor: 'rgba(60,77,99,0.32) transparent',
                        '&::-webkit-scrollbar': {
                            width: 6,
                        },
                        '&::-webkit-scrollbar-track': {
                            background: 'transparent',
                        },
                        '&::-webkit-scrollbar-thumb': {
                            backgroundColor: 'rgba(60,77,99,0.32)',
                            borderRadius: 999,
                        },
                        '&::-webkit-scrollbar-thumb:hover': {
                            backgroundColor: 'rgba(60,77,99,0.45)',
                        },
                    }}
                >
                    {/* Breadcrumbs */}
                    <Breadcrumbs
                        aria-label="breadcrumb"
                        sx={{ mb: 2, '& .MuiBreadcrumbs-separator': { mx: 1 } }}
                    >
                        <Link
                            component={RouterLink}
                            to="/"
                            underline="hover"
                            color="inherit"
                            sx={{ fontSize: '0.875rem' }}
                        >
                            {t('eventPage.breadcrumb.home', 'Home')}
                        </Link>
                        <Link
                            component={RouterLink}
                            to="/calendar"
                            underline="hover"
                            color="inherit"
                            sx={{ fontSize: '0.875rem' }}
                        >
                            {t('eventPage.breadcrumb.calendar', 'Calendar')}
                        </Link>
                        <Typography color="text.primary" sx={{ fontSize: '0.875rem' }}>
                            {event.name}
                        </Typography>
                    </Breadcrumbs>

                    {/* Header */}
                    <Paper
                        elevation={0}
                        sx={{
                            p: { xs: 2, md: 4 },
                            mb: 3,
                            borderRadius: 2,
                            bgcolor: 'background.paper',
                            border: '1px solid',
                            borderColor: 'divider',
                        }}
                    >
                        {/* Back button */}
                        <Button
                            startIcon={<ArrowBackIcon />}
                            onClick={handleBackToCalendar}
                            sx={{ mb: 2, textTransform: 'none' }}
                            size="small"
                        >
                            {t('eventPage.backToCalendar', 'Back to Calendar')}
                        </Button>

                        {/* Event name + chips */}
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 2, mb: 2 }}>
                            <Typography
                                variant="h1"
                                sx={{
                                    fontSize: { xs: '1.5rem', sm: '2rem', md: '2.5rem' },
                                    fontWeight: 700,
                                    color: 'text.primary',
                                    lineHeight: 1.2,
                                }}
                            >
                                {event.name}
                            </Typography>
                            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                                <Chip
                                    label={t(`impacts.${event.impact}Impact`, event.impact?.charAt(0).toUpperCase() + event.impact?.slice(1) + ' Impact')}
                                    size="small"
                                    sx={{
                                        bgcolor: impactStyle.bg,
                                        color: impactStyle.text,
                                        fontWeight: 600,
                                        textTransform: 'capitalize',
                                    }}
                                />
                                {event.category && (
                                    <Chip
                                        label={event.category}
                                        size="small"
                                        variant="outlined"
                                        icon={<CategoryIcon sx={{ fontSize: '1rem' }} />}
                                    />
                                )}
                            </Box>
                        </Box>

                        {/* Description */}
                        <Typography
                            variant="body1"
                            sx={{
                                fontSize: { xs: '1rem', md: '1.125rem' },
                                lineHeight: 1.7,
                                color: 'text.secondary',
                                mb: 2,
                            }}
                        >
                            {localizedContent.description}
                        </Typography>

                        {/* Quick info chips */}
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                            {event.frequency && (
                                <Chip
                                    icon={<ScheduleIcon sx={{ fontSize: '1rem' }} />}
                                    label={event.frequency}
                                    size="small"
                                    variant="outlined"
                                />
                            )}
                            {event.source && (
                                <Chip
                                    icon={<SourceIcon sx={{ fontSize: '1rem' }} />}
                                    label={event.source}
                                    size="small"
                                    variant="outlined"
                                />
                            )}
                        </Box>
                    </Paper>

                    {/* Content Grid */}
                    <Grid container spacing={3}>
                        {/* Trading Implications */}
                        {localizedContent.tradingImplication && (
                            <Grid size={{ xs: 12, md: 6 }}>
                                <InfoCard
                                    icon={<TrendingUpIcon color="primary" />}
                                    title={t('eventPage.tradingImplication', 'Trading Implications')}
                                >
                                    <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.7 }}>
                                        {localizedContent.tradingImplication}
                                    </Typography>
                                </InfoCard>
                            </Grid>
                        )}

                        {/* Release Time */}
                        {localizedContent.releaseTime && (
                            <Grid size={{ xs: 12, md: 6 }}>
                                <InfoCard
                                    icon={<ScheduleIcon color="primary" />}
                                    title={t('eventPage.releaseSchedule', 'Release Schedule')}
                                >
                                    <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.7 }}>
                                        {localizedContent.releaseTime}
                                    </Typography>
                                </InfoCard>
                            </Grid>
                        )}

                        {/* Key Thresholds */}
                        {localizedContent.keyThresholds &&
                            Object.keys(localizedContent.keyThresholds).length > 0 && (
                                <Grid size={{ xs: 12, md: 6 }}>
                                    <InfoCard
                                        icon={<ShowChartIcon color="primary" />}
                                        title={t('eventPage.keyThresholds', 'Key Thresholds')}
                                    >
                                        <KeyThresholdsDisplay thresholds={localizedContent.keyThresholds} t={t} />
                                    </InfoCard>
                                </Grid>
                            )}

                        {/* View on Calendar CTA */}
                        <Grid size={{ xs: 12, md: 6 }}>
                            <InfoCard
                                icon={<CalendarIcon color="primary" />}
                                title={t('eventPage.viewOnCalendar', 'View on Calendar')}
                            >
                                <Typography variant="body2" color="text.secondary" sx={{ mb: 2, lineHeight: 1.7 }}>
                                    {t(
                                        'eventPage.calendarCta',
                                        'See upcoming dates for this event and set reminders on our economic calendar.'
                                    )}
                                </Typography>
                                <Button
                                    variant="contained"
                                    startIcon={<CalendarIcon />}
                                    onClick={handleBackToCalendar}
                                    sx={{ textTransform: 'none' }}
                                >
                                    {t('eventPage.goToCalendar', 'Go to Calendar')}
                                </Button>
                            </InfoCard>
                        </Grid>
                    </Grid>

                    {/* Aliases (if any) */}
                    {event.aliases && event.aliases.length > 0 && (
                        <Paper
                            elevation={0}
                            sx={{
                                p: { xs: 2, md: 3 },
                                mt: 3,
                                borderRadius: 2,
                                bgcolor: 'background.default',
                                border: '1px solid',
                                borderColor: 'divider',
                            }}
                        >
                            <Typography variant="subtitle2" fontWeight={600} sx={{ mb: 1.5 }}>
                                {t('eventPage.alsoKnownAs', 'Also Known As')}
                            </Typography>
                            <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                                {event.aliases.map((alias, idx) => (
                                    <Chip key={idx} label={alias} size="small" variant="outlined" />
                                ))}
                            </Box>
                        </Paper>
                    )}
                </Box>
            </PublicLayout>

            {/* Modals */}
            <Suspense fallback={null}>
                <SettingsSidebar2
                    open={settingsOpen}
                    onClose={handleCloseSettings}
                    onOpenAuth={handleOpenAuth}
                />
                <AuthModal2 open={authModalOpen} onClose={handleCloseAuth} />
            </Suspense>
        </>
    );
}
